export const articlesData = [
	{
		title: 'Археологи нашли в Сирии ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'Philipp Fürhofer',
		bigImage: '/img/articles.jpg',
		smallImage: '/img/tinyArticles.jpg',
	},
	{
		title: 'Археологи нашли в Египте ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'John',
		bigImage: '/img/articles_2.jpg',
		smallImage: '/img/articles_2.jpg',
	},
	{
		title: 'Археологи нашли в Турции ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'Alan',
		bigImage: '/img/articles_3.avif',
		smallImage: '/img/articles_3.avif',
	},
	{
		title: 'Археологи нашли в Крыму ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'Philipp',
		bigImage: '/img/articles_2.jpg',
		smallImage: '/img/articles_2.jpg',
	},
	{
		title: 'Археологи нашли в Сирии ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'Philipp Fürhofer',
		bigImage: '/img/articles_3.avif',
		smallImage: '/img/articles_3.avif',
	},
	{
		title: 'Археологи нашли в Сирии ранее неизвестный римский порт',
		description: 'The Sculpture Collection, with its rich and unique exhibits, presents the evolution of ancient Greek sculpture from 700 BC to the 5th century AD. The core of the Collection was formed in 1874 when sculptures from the temporary archaeological collections of Athens were gradually transferred to the Archaeological Museum that was under construction. The neoclassical building also housed most of the antiquities retrieved by accident. The gradual handing over of antiquities recovered during excavation or acquired by the Archaeological Society (1884-1893) and also the relocation to the Museum of the most significant sculptures of the provinces contributed decisively to the enrichment of the Collection which nowadays numbers approximately 16.000 sculptures . ',
		shortDescription: 'Находка была сделана в рамках сирийской археологической экспедиции недалеко от Тартуса, сирийского города на побережье Средиземного моря.',
		dayOfPublication: 16,
		monthOfPublication: 10,
		yearOfPublication: 2023,
		author: 'Philipp Fürhofer',
		bigImage: '/img/articles.jpg',
		smallImage: '/img/tinyArticles.jpg',
	},
];